spring:
  application:
    name: multitenancy-testing
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/<DUMMY-A>/v2.0
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/<DUMMY-A>/v2.0
            token-uri: "https://login.microsoftonline.com/organizations/oauth2/v2.0/token"
            authorization-uri: "https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize"
            jwk-set-uri: https://login.microsoftonline.com/organizations/discovery/v2.0/keys
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: xxx
            client-secret: xxx         
            scope:
            - https://graph.microsoft.com/User.ReadBasic.All
            - openid
            - email
            - profile
